# Generated by Django 6.1.2 on 2026-10-07 03:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sueldo', models.PositiveIntegerField(help_text='En pesos, sin puntos.', verbose_name='Sueldo líquido mensual')),
                ('frecuencia_pago', models.CharField(choices=[('mensual', 'Mensual'), ('quincena', 'Quincena'), ('variable', 'Variable')], max_length=10, verbose_name='Frecuencia de pago')),
                ('meta_ahorro', models.PositiveSmallIntegerField(help_text='Porcentaje del sueldo que quieres ahorrar.', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Meta de ahorro (%)')),
                ('rut', models.CharField(help_text='Ej: 12.345.678-9', max_length=12, verbose_name='RUT')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=30)),
                ('fecha', models.DateTimeField()),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12)),
                ('monto', models.PositiveIntegerField()),
                ('codigo', models.CharField(max_length=30, verbose_name='Código de operación')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('gasto', 'Gasto')], max_length=7)),
                ('es_propia', models.BooleanField(default=False, verbose_name='Entre tus cuentas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'banco', 'codigo'), name='movimiento_unico')],
            },
        ),
    ]
