# Generated by Django 6.1.2 on 2026-10-07 03:37

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        # Permite buscar sin tildes: "matias" encuentra "Matías"
        UnaccentExtension(),
    ]
